spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/web_service_project_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.jdbc.Driver
    username: PB
    password: password
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
server:
  error:
    include-message: always
    include-binding-errors: always
#cache:
#  client:
#    ttl: 30


